rails-less/base_app-final/config/routes.rb
Rails.application.routes.draw do
  post 'fill_result_form' => 'surveys#fill_result_form'
  post 'fill_ward_form' => 'surveys#fill_ward_form'
  post 'fill_card_form' => 'surveys#fill_card_form'

  resources :results
  resources :surveys
  resources :wards
  resources :cards do
     collection do
       get :search
     end
   end
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

rails-less/base_app-final/app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :result
  belongs_to :card
  belongs_to :ward
  validates :cause, presence:true, length: {maximum: 128}
  validates :entered, presence:true
  validates :ended, presence:true
  validates :epicrisis, presence:true, length: {maximum: 128}

  accepts_nested_attributes_for :ward,
    allow_destroy: true

  accepts_nested_attributes_for :result,
    allow_destroy: true

  accepts_nested_attributes_for :card,
    allow_destroy: true

end

rails-less/base_app-final/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  def fill_result_form
    id = params[:result_id].to_i
    if id > 0
      @result = Result.find(id)
    else
      @result = nil
    end
    respond_to do |format|
      format.js
    end
  end

  def fill_card_form
    id = params[:card_id].to_i
    if id > 0
      @card = Card.find(id)
    else
      @card = nil
    end
    respond_to do |format|
      format.js
    end
  end

  def fill_ward_form
    id = params[:ward_id].to_i
    if id > 0
      @ward = Ward.find(id)
    else
      @ward = nil
    end
    respond_to do |format|
      format.js
    end
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:card_id, :result_id, :ward_id, :cause, :entered, :ended, :epicrisis,
      ward_attributes: [:id, :department, :floor, :capacity, :number, :num_of_pacients],
      result_attributes: [:id, :conclusion, :title, :rdate, :appointment, :causes, :first_inspection, :results],
      card_attributes: [:id, :second_name, :first_name, :last_name, :passport, :insurance, :residence, :created, :allergy, :cart_number])
    end
end

rails-less/base_app-final/app/helpers/surveys_helper.rb
module SurveysHelper
end

rails-less/base_app-final/app/views/surveys/_card_fields.html.haml
.form-group
  .row
    .col-md-6
      .form-group
        = f.label :second_name
        = f.text_field :second_name, class: 'form-control'
        = f.error_messages_for(:second_name)
  .row
    .col-md-6
      .form-group
        = f.label :first_name
        = f.text_field :first_name, class: 'form-control'
        = f.error_messages_for(:first_name)
  .row
    .col-md-6
      .form-group
        = f.label :last_name
        = f.text_field :last_name, class: 'form-control'
        = f.error_messages_for(:last_name)
  .row
    .col-md-6
      .form-group
        = f.label :passport
        = f.text_field :passport, class: 'form-control'
        = f.error_messages_for(:passport)
  .row
    .col-md-6
      .form-group
        = f.label :insurance
        = f.number_field :insurance, class: 'form-control'
        = f.error_messages_for(:insurance)
  .row
    .col-md-6
      .form-group
        = f.label :residence
        = f.text_field :residence, class: 'form-control'
        = f.error_messages_for(:residence)
  .row
    .col-md-6
      .form-group
        = f.label :created
        .input-group.date.datepicker
          = f.text_field(:created, value: lnil(f.object.created),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:created)
  .row
    .col-md-6
      .form-group
        = f.label :allergy
        = f.text_field :allergy, class: 'form-control'
        = f.error_messages_for(:allergy)
  .row
    .col-md-6
      .form-group
        = f.label :cart_number
        = f.number_field :cart_number, class: 'form-control'
        = f.error_messages_for(:cart_number)
        = f.hidden_field :id ,class: 'form-control'

rails-less/base_app-final/app/views/surveys/_department_fields.html.haml
.form-group
  .row
    .col-md-6
      = f.label :'Название департамента'
      = f.text_field :name, class: 'form-control'
      = f.error_messages_for(:name)
      = f.hidden_field :id ,class: 'form-control'

rails-less/base_app-final/app/views/surveys/_form.html.haml
= form_for @survey do |f|
  = error_messages_for @survey
  .row
    .col-md-6
      .form-group
        = f.label :cause
        = f.text_field :cause
  .row
    .col-md-6
      .form-group
        = f.label :entered
        .input-group.date.datepicker
          = f.text_field(:entered, value: lnil(f.object.entered),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:entered)
  .row
    .col-md-6
      .form-group
        = f.label :ended
        .input-group.date.datepicker
          = f.text_field(:ended, value: lnil(f.object.ended),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:ended)
  .row
    .col-md-6
      .form-group
        = f.label :epicrisis
        = f.text_field :epicrisis

  %h3= "Выберите результат или создайте новый"
  .row
    .col-md-6
      = f.label :result_id
      = f.collection_select :result_id, Result.all, :id, :title,
      {include_blank: true}, {id: 'select_existing_result', class: 'form-control'}
      = f.error_messages_for(:result_id)
      = f.fields_for :result, f.object.result_id || f.object.build_result do |result|
        = render 'result_fields', f: result

  %h3= "Выберите карту больного или создайте новую"
  .row
    .col-md-6
      = f.label :card_id
      = f.collection_select :card_id, Card.all, :id, :cart_number,
      {include_blank: true}, {id: 'select_existing_card', class: 'form-control'}
      = f.error_messages_for(:card_id)
      = f.fields_for :card, f.object.card_id || f.object.build_card do |card|
        = render 'card_fields', f: card

  %h3= "Выберите палату или создайте новую"
  .row
    .col-md-6
      = f.label :ward_id
      = f.collection_select :ward_id, Ward.all, :id, :number,
      {include_blank: true}, {id: 'select_existing_ward', class: 'form-control'}
      = f.error_messages_for(:ward_id)
      = f.fields_for :ward, f.object.ward_id || f.object.build_ward do |ward|
        = render 'ward_fields', f: ward

  - if params[:action] == 'edit'
    - if !f.object.new_record?
      = link_to @survey.ward,
      :method => :delete,
      :data => { :confirm => t('buttons.confirm.result') },
      class: 'btn btn-danger' do
        = fa_icon :times
        = t('buttons.destroy')
  %p
  - if is_admin?
    .form-actions.bottom20
      = f.submit nil, class: 'btn btn-primary'
  - else
    %h3 Вносить изменения(регистрировать новые) может только администратор

rails-less/base_app-final/app/views/surveys/_result_fields.html.haml
.form-group
  .row
    .col-md-6
      .form-group
        = f.label :conclusion
        = f.text_field :conclusion, class: 'form-control'
        = f.error_messages_for(:conclusion)
  .row
    .col-md-6
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
        = f.error_messages_for(:title)
  .row
    .col-md-6
      .form-group
        = f.label :rdate
        .input-group.date.datepicker
          = f.text_field(:rdate, value: lnil(f.object.rdate),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:rdate)
  .row
    .col-md-6
      .form-group
        = f.label :appointment
        = f.text_field :appointment, class: 'form-control'
        = f.error_messages_for(:appointment)
  .row
    .col-md-6
      .form-group
        = f.label :causes
        = f.text_field :causes, class: 'form-control'
        = f.error_messages_for(:causes)
  .row
    .col-md-6
      .form-group
        = f.label :first_inspection
        = f.text_field :first_inspection, class: 'form-control'
        = f.error_messages_for(:first_inspection)
  .row
    .col-md-6
      .form-group
        = f.label :results
        = f.text_field :results, class: 'form-control'
        = f.error_messages_for(:results)
        = f.hidden_field :id ,class: 'form-control'

rails-less/base_app-final/app/views/surveys/_ward_fields.html.haml
.form-group
  .row
    .col-md-6
      .form-group
        = f.label :department
        = f.number_field :department, class: 'form-control'
        = f.error_messages_for(:department)
  .row
    .col-md-6
      .form-group
        = f.label :floor
        = f.number_field :floor, class: 'form-control'
        = f.error_messages_for(:floor)
  .row
    .col-md-6
      .form-group
        = f.label :capacity
        = f.number_field :capacity, class: 'form-control'
        = f.error_messages_for(:capacity)
  .row
    .col-md-6
      .form-group
        = f.label :number
        = f.number_field :number, class: 'form-control'
        = f.error_messages_for(:number)
  .row
    .col-md-6
      .form-group
        = f.label :num_of_pacients
        = f.number_field :num_of_pacients, class: 'form-control'
        = f.error_messages_for(:num_of_pacients)
        = f.hidden_field :id ,class: 'form-control'

rails-less/base_app-final/app/views/surveys/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.surveys.edit')
  %li
    = link_to(@survey.epicrisis, @survey)
  %li
    = link_to 'Амбулаторные периоды', surveys_path
  %li
    Больница

.page-header
  %h1= t('headers.surveys.edit')

= render 'form'

rails-less/base_app-final/app/views/surveys/index.html.haml
=breadcrumb_tag do
  %li.active
    Амбулаторные периоды
  %li
    Больница

%h1= t('app.surveys.index')

- if is_admin?
  = link_to new_survey_path, class: 'btn btn-success' do
    = fa_icon :plus
    = t('buttons.new.card')
.table-responsive
  %table.table.table-hover.table-striped.center
    %caption
    %thead
      %tr
        %th= Survey.human_attribute_name(:card)
        %th= Survey.human_attribute_name(:result)
        %th= Survey.human_attribute_name(:ward)
        %th= Survey.human_attribute_name(:cause)
        %th= Survey.human_attribute_name(:entered)
        %th= Survey.human_attribute_name(:ended)
        %th= Survey.human_attribute_name(:epicrisis)
        %th.p50
        %th.p50
        %th.p50

    %tbody

      - @surveys.each do |survey|
        %tr
          %td{:data => {:label => (Survey.human_attribute_name(:card_id))}}
            = survey.card.cart_number
          %td{:data => {:label => (Survey.human_attribute_name(:result_id))}}
            = survey.result.title
          %td{:data => {:label => (Survey.human_attribute_name(:ward_id))}}
            = survey.ward.number
          %td{:data => {:label => (Survey.human_attribute_name(:cause))}}
            = survey.cause
          %td{:data => {:label => (Survey.human_attribute_name(:entered))}}
            = survey.entered
          %td{:data => {:label => (Survey.human_attribute_name(:ended))}}
            = survey.ended
          %td{:data => {:label => (Survey.human_attribute_name(:epicrisis))}}
            = survey.epicrisis
            
          %td.right
            = link_to survey, class: 'btn btn-success' do
              = fa_icon :eye
          - if is_admin?
            %td.right
              = link_to edit_survey_path(survey), class: 'btn btn-info' do
                = fa_icon :edit
          - if is_admin?
            %td.right
              = link_to survey, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
                = fa_icon :times

rails-less/base_app-final/app/views/surveys/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.surveys.edit')
  %li
    = link_to 'Амбулаторный периоды', surveys_path
  %li
    Больница
    
.page-header
  %h1= t('headers.surveys.new')
= render 'form'

rails-less/base_app-final/app/views/surveys/show.html.haml
=breadcrumb_tag do
  %li.active
    = @survey.id
  %li
    = link_to 'Амбулаторные периоды', surveys_path
  %li
    Больница

%h1= @Survey_id

%dl
  %dt= Survey.human_attribute_name(:card)
  %dd= @survey.card_id
  %dt= Survey.human_attribute_name(:result)
  %dd= @survey.result_id
  %dt= Survey.human_attribute_name(:ward)
  %dd= @survey.ward_id
  %dt= Survey.human_attribute_name(:cause)
  %dd= @survey.cause
  %dt= Survey.human_attribute_name(:entered)
  %dd= @survey.entered
  %dt= Survey.human_attribute_name(:ended)
  %dd= @survey.ended
  %dt= Survey.human_attribute_name(:epicrisis)
  %dd= @survey.epicrisis